_extends: .github
repository:
  name: eslint-config-cypress
  description: Shareable config for ESLint for projects that use Cypress
  homepage: 'https://npm.im/@pragmatic-divops/eslint-config-cypress'
  private: false
